- name: Playbook to Update All Server Packages
  hosts: servers
  become: true
  gather_facts: true
  order: sorted
  tasks:
    - name: Update apt repo
      apt: update_cache=yes force_apt_get=yes cache_valid_time=3600

    - name: Upgrade all packages
      apt: upgrade=dist force_apt_get=yes

    - name: autoremove all old packages
      apt:
        autoremove: true
        purge: true

    - name: Check if reboot required
      stat:
        path: /var/run/reboot-required
      register: reboot_required_file

    - name: Reboot if required
      reboot:
      when: reboot_required_file.stat.exists == true
